# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 05:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='\u0423\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440 \u0438\u0437 \u04422')),
                ('ls', models.CharField(max_length=10, verbose_name='\u041b\u0438\u0446\u0435\u0432\u043e\u0439 \u0441\u0447\u0435\u0442')),
                ('name', models.CharField(max_length=150, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u043f\u043e\u0442\u0440\u0435\u0431\u0438\u0442\u0435\u043b\u044f')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='\u0418\u041d\u041d')),
                ('kpp', models.CharField(blank=True, max_length=20, verbose_name='\u041a\u041f\u041f')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name=b'\xd0\xa2\xd0\xb8\xd0\xbf \xd0\xbf\xd0\xbe\xd1\x82\xd1\x80\xd0\xb5\xd0\xb1\xd0\xb8\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8f')),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0441\u0447\u0435\u0442\u0447\u0438\u043a\u0430')),
                ('date_created', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u0433\u043e\u0442\u043e\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('date_checked', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0438')),
                ('last_date_instrumental', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0439 \u0438\u043d\u0441\u0442\u0440\u0443\u043c\u0435\u043d\u0442\u0430\u043b\u044c\u043d\u043e\u0439 \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0438')),
                ('next_date_instrumental', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0439 \u0438\u043d\u0441\u0442\u0440\u0443\u043c\u0435\u043d\u0442\u0430\u043b\u044c\u043d\u043e\u0439 \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0438')),
                ('comment', models.TextField(blank=True, max_length=128, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
            ],
        ),
        migrations.CreateModel(
            name='MeterCorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwh', models.DecimalField(decimal_places=5, default=0, max_digits=17, verbose_name='\u041a\u043e\u0440\u0440\u0435\u043a\u0442\u0438\u0440\u043e\u0432\u043a\u0430 \u0432 kwh')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.Meter')),
            ],
        ),
        migrations.CreateModel(
            name='MeterPassport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u0441\u0447\u0435\u0442\u0447\u0438\u043a\u0430')),
                ('old_id', models.PositiveIntegerField(db_index=True, null=True, verbose_name='\u0421\u0442\u0430\u0440\u044b\u0439 id')),
                ('check', models.BooleanField(verbose_name='\u041f\u0440\u043e\u0432\u0435\u0440\u0435\u043d\u043d\u044b\u0439')),
                ('active', models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u044b\u0439')),
                ('digits', models.PositiveSmallIntegerField(verbose_name='\u0426\u0435\u043b\u0430\u044f \u0447\u0430\u0441\u0442\u044c')),
                ('decimals', models.PositiveSmallIntegerField(verbose_name='\u0414\u0440\u043e\u0431\u043d\u0430\u044f \u0447\u0430\u0441\u0442\u044c')),
                ('accuracy_class', models.PositiveSmallIntegerField(choices=[(4, b'1.0'), (5, b'0.5'), (3, b'1.5'), (1, b'2.5 \xd0\xb8 \xd0\xb1\xd0\xbe\xd0\xbb\xd1\x8c\xd1\x88\xd0\xb5'), (7, b'0.2'), (6, b'0.5S'), (2, b'2.0'), (8, b'0.2S'), (0, b'\xd1\x84\xd0\xb8\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2\xd0\xbd\xd1\x8b\xd0\xb9')], verbose_name='\u041a\u043b\u0430\u0441\u0441 \u0442\u043e\u0447\u043d\u043e\u0441\u0442\u0438')),
                ('check_period', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u041f\u0435\u0440\u0438\u043e\u0434 \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0438')),
                ('replace_period', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u041f\u0435\u0440\u0438\u043e\u0434 \u0437\u0430\u043c\u0435\u043d\u044b')),
                ('voltage', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u041d\u0430\u043f\u0440\u044f\u0436\u0435\u043d\u0438\u0435')),
                ('amperage', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u0422\u043e\u043a')),
                ('type_of_energy', models.PositiveSmallIntegerField(choices=[(0, b'\xd0\x90\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2\xd0\xbd\xd1\x8b\xd0\xb9'), (1, b'\xd0\xa0\xd0\xb5\xd0\xb0\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2\xd0\xbd\xd1\x8b\xd0\xb9'), (2, b'\xd0\x90\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2\xd0\xbd\xd0\xbe-\xd1\x80\xd0\xb5\xd0\xb0\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2\xd0\xbd\xd1\x8b\xd0\xb9')], verbose_name='\u0412\u0438\u0434 \u044d\u043d\u0435\u0440\u0433\u0438\u0438')),
                ('type_of_meter', models.PositiveSmallIntegerField(choices=[(1, b'\xd0\xad\xd0\xbb\xd0\xb5\xd0\xba\xd1\x82\xd1\x80\xd0\xbe\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9'), (0, b'\xd0\x98\xd0\xbd\xd0\xb4\xd1\x83\xd0\xba\xd1\x86\xd0\xb8\xd0\xbe\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9')], verbose_name='\u0422\u0438\u043f \u0441\u0447\u0435\u0442\u0447\u0438\u043a\u0430')),
                ('tariff', models.PositiveSmallIntegerField(choices=[(0, b'\xd0\x9e\xd0\xb4\xd0\xbd\xd0\xbe\xd1\x82\xd0\xb0\xd1\x80\xd0\xb8\xd1\x84\xd0\xbd\xd1\x8b\xd0\xb9'), (1, b'\xd0\x9c\xd0\xbd\xd0\xbe\xd0\xb3\xd0\xbe\xd1\x82\xd0\xb0\xd1\x80\xd0\xb8\xd1\x84\xd0\xbd\xd1\x8b\xd0\xb9(\xd0\x97\xd0\xbe\xd0\xbd\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb9)')], verbose_name='\u0422\u0430\u0440\u0438\u0444\u043d\u043e\u0441\u0442\u044c')),
                ('phase', models.PositiveSmallIntegerField(choices=[(1, b'\xd0\xa2\xd1\x80\xd0\xb5\xd1\x85\xd1\x84\xd0\xb0\xd0\xb7\xd0\xbd\xd1\x8b\xd0\xb9'), (0, b'\xd0\x9e\xd0\xb4\xd0\xbd\xd0\xbe\xd1\x84\xd0\xb0\xd0\xb7\xd0\xbd\xd1\x8b\xd0\xb9')], verbose_name='\u0424\u0430\u0437\u0430')),
                ('direct', models.PositiveSmallIntegerField(choices=[(2, b'\xd0\x94\xd0\xb2\xd1\x83\xd0\xbd\xd0\xb0\xd0\xbf\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9'), (1, b'\xd0\x9e\xd0\xb4\xd0\xbd\xd0\xbe\xd0\xbd\xd0\xb0\xd0\xbf\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9')], verbose_name='\u041d\u0430\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u0435')),
                ('comment', models.TextField(blank=True, max_length=182, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_true', models.BooleanField(default=False, verbose_name='\u041f\u0440\u0438\u043d\u0438\u043c\u0430\u0442\u044c \u043f\u043e\u043a\u0430\u0437\u0430\u043d\u0438\u0435')),
                ('reading', models.DecimalField(decimal_places=5, default=0, max_digits=17, verbose_name='\u041f\u043e\u043a\u0430\u0437\u0430\u043d\u0438\u0435 \u0441\u0447\u0435\u0442\u0447\u0438\u043a\u0430')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReadingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('priority', models.PositiveSmallIntegerField(unique=True, verbose_name='\u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442 \u043f\u043e\u043a\u0430\u0437\u0430\u043d\u0438\u0439')),
            ],
        ),
        migrations.CreateModel(
            name='MeterSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_hours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0447\u0430\u0441\u043e\u0432 \u0440\u0430\u0431\u043e\u0442\u044b')),
                ('type_of_energy', models.PositiveSmallIntegerField(choices=[(0, b'\xd0\x90\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2\xd0\xbd\xd1\x8b\xd0\xb9'), (1, b'\xd0\xa0\xd0\xb5\xd0\xb0\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2\xd0\xbd\xd1\x8b\xd0\xb9')], verbose_name='\u0412\u0438\u0434 \u044d\u043d\u0435\u0440\u0433\u0438\u0438')),
                ('direction_energy', models.PositiveSmallIntegerField(choices=[(1, b'\xd0\x9e\xd1\x82\xd0\xbf\xd1\x83\xd1\x81\xd0\xba \xd0\xb2 \xd1\x81\xd0\xb5\xd1\x82\xd1\x8c'), (0, b'\xd0\x92\xd0\xbe\xd0\xb7\xd0\xb2\xd1\x80\xd0\xb0\xd1\x82 \xd0\xb2 \xd1\x81\xd0\xb5\xd1\x82\xd1\x8c')], verbose_name='\u041d\u0430\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u044d\u043d\u0435\u0440\u0433\u0438\u0438')),
                ('meter_place', models.PositiveSmallIntegerField(choices=[(2, b'\xd0\xb7\xd0\xb0 \xd0\xb3\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x86\xd0\xb5\xd0\xb9'), (0, b'\xd0\xbd\xd0\xb0 \xd0\xb3\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x86\xd0\xb5'), (1, b'\xd0\xb4\xd0\xbe \xd0\xb3\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x86\xd0\xb5')], verbose_name='\u041c\u0435\u0441\u0442\u043e \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0438 \u0441\u0447\u0435\u0442\u0447\u0438\u043a\u0430')),
                ('is_control', models.BooleanField(default=False, verbose_name='\u041a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u044b\u0439 \u0441\u0447\u0435\u0442\u0447\u0438\u043a')),
                ('c_trans', models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='\u041a\u043e\u044d\u0444\u0444\u0438\u0446\u0438\u0435\u043d\u0442\u0440 \u0442\u0440\u0430\u043d\u0441\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u0438')),
                ('c_loss', models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='\u041a\u043e\u044d\u0444\u0444\u0438\u0446\u0438\u0435\u043d\u0442\u0440 \u043f\u043e\u0442\u0435\u0440\u044c')),
                ('transformer_loss', models.DecimalField(blank=True, decimal_places=4, default=1, max_digits=12, null=True, verbose_name='\u041f\u043e\u0442\u0435\u0440\u0438 \u0432 \u0442\u0440\u0430\u043d\u0441\u0444\u043e\u0440\u043c\u0430\u0442\u043e\u0440\u0435')),
                ('cosfi', models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True, verbose_name='\u041a\u043e\u044d\u0444\u0444\u0438\u0446\u0438\u0435\u043d\u0442\u0440 \u0442\u0440\u0430\u043d\u0441\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u0438')),
                ('tangfi', models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True, verbose_name='\u041a\u043e\u044d\u0444\u0444\u0438\u0446\u0438\u0435\u043d\u0442\u0440 \u0442\u0440\u0430\u043d\u0441\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u0438')),
                ('wire_length', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.001), django.core.validators.MaxValueValidator(999)], verbose_name='\u0414\u043b\u0438\u043d\u0430 \u043f\u0440\u043e\u0432\u043e\u0434\u0430, \u0432 \u043a\u043c')),
                ('wire_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.005), django.core.validators.MaxValueValidator(1000)], verbose_name='\u041d\u0430\u043f\u0440\u044f\u0436\u0435\u043d\u0438\u0435 \u043b\u0438\u043d\u0438\u0438, \u0432 \u043a\u0412')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u0432\u043e\u0430\u043d\u0438\u0435 \u0441\u0435\u0442\u0435\u0432\u043e\u0439 \u043e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u0438')),
            ],
        ),
        migrations.CreateModel(
            name='Orum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrumCorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwh', models.DecimalField(decimal_places=5, default=0, max_digits=17, verbose_name='\u041a\u043e\u0440\u0440\u0435\u043a\u0442\u0438\u0440\u043e\u0432\u043a\u0430 \u0432 kwh')),
                ('orum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.Orum')),
            ],
        ),
        migrations.CreateModel(
            name='OrumDateUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_use', models.PositiveIntegerField(verbose_name='\u0414\u043d\u0435\u0439')),
                ('orum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.Orum')),
            ],
        ),
        migrations.CreateModel(
            name='OrumSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.DecimalField(decimal_places=5, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(1000000)], verbose_name='\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043d\u0430\u044f \u043c\u043e\u0449\u043d\u043e\u0441\u0442\u044c')),
                ('hours', models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='\u0427\u0430\u0441\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('ratio', models.DecimalField(decimal_places=6, default=1, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='\u041a\u043e\u044d\u0444\u0444\u0438\u0446\u0435\u043d\u0442 \u043f\u043e\u0442\u0440\u0435\u0431\u043b\u0435\u043d\u0438\u044f')),
            ],
        ),
        migrations.CreateModel(
            name='OrumType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=31, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb8\xd0\xbc\xd0\xb5\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('formula', models.IntegerField(choices=[(2, b'\xd0\xa0\xd0\xb0\xd1\x81\xd1\x85\xd0\xbe\xd0\xb4 * \xd0\x9a\xd0\xbe\xd0\xbb\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd0\xbe \xd0\xb4\xd0\xbd\xd0\xb5\xd0\xb9'), (3, b'\xd0\xa0\xd0\xb0\xd1\x81\xd1\x85\xd0\xbe\xd0\xb4 * \xd0\x9a\xd0\xbe\xd0\xbb\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd0\xbe \xd0\xb4\xd0\xbd\xd0\xb5\xd0\xb9 * \xd0\xa7\xd0\xb0\xd1\x81\xd1\x8b'), (1, b'\xd0\x9f\xd0\xbe\xd1\x81\xd1\x82\xd0\xbe\xd1\x8f\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9 \xd1\x80\xd0\xb0\xd1\x81\xd1\x85\xd0\xbe\xd0\xb4')], verbose_name=b'\xd0\xa4\xd0\xbe\xd1\x80\xd0\xbc\xd1\x83\xd0\xbb\xd0\xb0')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb8\xd0\xbc\xd0\xb5\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xbf\xd0\xb5\xd1\x80\xd0\xb8\xd0\xbe\xd0\xb4\xd0\xb0')),
                ('date_start', models.DateField(verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbd\xd0\xb0\xd1\x87\xd0\xb0\xd0\xbb\xd0\xb0 \xd0\xbf\xd0\xb5\xd1\x80\xd0\xb8\xd0\xbe\xd0\xb4\xd0\xb0')),
                ('faza_id', models.IntegerField(help_text=b'\xd0\xa8\xd0\xb0\xd0\xb1\xd0\xbb\xd0\xbe\xd0\xbd yyyymm(201501)', verbose_name=b'ID \xd0\xbf\xd0\xb5\xd1\x80\xd0\xb8\xd0\xbe\xd0\xb4\xd0\xbe\xd0\xb2 \xd0\xb2 \xd1\x84\xd0\xb0\xd0\xb7\xd0\xb5')),
                ('last_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.Period')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u0442\u043e\u0447\u043a\u0438 \u0443\u0447\u0435\u0442\u0430')),
                ('consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.Consumer')),
            ],
        ),
        migrations.CreateModel(
            name='PointMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_in_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_point_meter_set', to='energy.Period')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.Meter')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.Point')),
                ('removed_in_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='removed_point_meter_set', to='energy.Period')),
            ],
        ),
        migrations.CreateModel(
            name='PowerGridRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb8\xd0\xbc\xd0\xb5\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xa0\xd0\xad\xd0\xa1\xd0\xb0')),
                ('current_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.Period')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb8\xd0\xbc\xd0\xb5\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd1\x83\xd1\x87\xd0\xb0\xd1\x81\xd1\x82\xd0\xba\xd0\xb0')),
                ('power_grid_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.PowerGridRegion')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u0432\u043e\u0430\u043d\u0438\u0435 \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0441\u0442\u0432\u0435\u043d\u043d\u043e\u0433\u043e \u043e\u0442\u0435\u0434\u0435\u043b\u0435\u043d\u0438\u044f')),
                ('network_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.NetworkOrganization')),
            ],
        ),
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.PositiveIntegerField(unique=True, verbose_name='\u0423\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440 \u0438\u0437 \u04422')),
                ('title', models.CharField(max_length=64, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u0442\u0440\u0430\u043d\u0441\u0444\u043e\u0440\u043c\u0430\u0442\u043e\u0440\u0430')),
                ('pxx', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='\u041f\u043e\u0442\u0435\u0440\u0438 \u0445\u043e\u043b\u043e\u0441\u0442\u043e\u0433\u043e \u0445\u043e\u0434\u0430(Pxx)')),
                ('pkz', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='\u041f\u043e\u0442\u0435\u0440\u0438 \u0432 \u043e\u0431\u043c\u043e\u0442\u043a\u0430\u0445(P\u043a\u0437)')),
                ('s', models.PositiveIntegerField(verbose_name='\u041d\u043e\u043c\u0438\u043d\u0430\u043b\u044c\u043d\u0430\u044f \u043c\u043e\u0449\u043d\u043e\u0441\u0442\u044c \u0442\u0440\u0430\u043d\u0441\u0444\u043e\u0440\u043c\u0430\u0442\u043e\u0440\u0430, \u043a\u0412\u0430')),
                ('comment', models.TextField(blank=True, max_length=128, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
            ],
        ),
        migrations.CreateModel(
            name='Wire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.PositiveIntegerField(unique=True, verbose_name='\u0423\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440 \u0438\u0437 \u04422')),
                ('title', models.CharField(max_length=64, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u043f\u0440\u043e\u0432\u043e\u0434\u0430')),
                ('ro', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='\u0423\u0434\u0435\u043b\u044c\u043d\u043e\u0435 \u0441\u043e\u043f\u0440\u043e\u0442\u0438\u0432\u043b\u0435\u043d\u0438\u0435 \u043f\u0440\u043e\u0432\u043e\u0434\u0430(ro)')),
                ('comment', models.TextField(blank=True, max_length=128, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
            ],
        ),
        migrations.AddField(
            model_name='powergridregion',
            name='production_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.ProductionDepartment'),
        ),
        migrations.AddField(
            model_name='orumsetting',
            name='installation_orum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installation_orum_setting_set', to='energy.Period'),
        ),
        migrations.AddField(
            model_name='orumsetting',
            name='orum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.Orum'),
        ),
        migrations.AddField(
            model_name='orumsetting',
            name='removed_orum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='removed_orum_setting_set', to='energy.Period'),
        ),
        migrations.AddField(
            model_name='orumsetting',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.OrumType'),
        ),
        migrations.AddField(
            model_name='orumdateuse',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.Period'),
        ),
        migrations.AddField(
            model_name='orumcorrection',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.Period'),
        ),
        migrations.AddField(
            model_name='orum',
            name='installation_in_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_in_period_set', to='energy.Period'),
        ),
        migrations.AddField(
            model_name='orum',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.Point'),
        ),
        migrations.AddField(
            model_name='orum',
            name='removed_in_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='removed_in_period_set', to='energy.Period'),
        ),
        migrations.AddField(
            model_name='metersetting',
            name='installation_meter_setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installation_meter_setting_set', to='energy.Period'),
        ),
        migrations.AddField(
            model_name='metersetting',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.Meter'),
        ),
        migrations.AddField(
            model_name='metersetting',
            name='removed_meter_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='removed_meter_setting_set', to='energy.Period'),
        ),
        migrations.AddField(
            model_name='metersetting',
            name='transformer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.Transformer'),
        ),
        migrations.AddField(
            model_name='metersetting',
            name='wire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.Wire'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.MeterReadingEvent'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.Meter'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.Period'),
        ),
        migrations.AddField(
            model_name='metercorrection',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.Period'),
        ),
        migrations.AddField(
            model_name='meter',
            name='passport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.MeterPassport'),
        ),
        migrations.AddField(
            model_name='meter',
            name='power_grid_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.PowerGridRegion'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='production_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.ProductionArea', verbose_name='\u041f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0441\u0442\u0432\u0435\u043d\u043d\u044b\u0439 \u0443\u0447\u0430\u0441\u0442\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.ConsumerType', verbose_name='\u0422\u0438\u043f \u043f\u043e\u0442\u0435\u0440\u0431\u0438\u0442\u0435\u043b\u044f'),
        ),
        migrations.AlterUniqueTogether(
            name='orumdateuse',
            unique_together=set([('orum', 'period')]),
        ),
    ]
