# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 10:40
from __future__ import unicode_literals
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    def load_orum_types(apps, shema_editor):
        import json
        files = [
            'energy/fixtures/energy_meter_reading_event.json',
            'energy/fixtures/energy_orum_type.json',
            'energy/fixtures/energy_period.json',
            'energy/fixtures/energy_meter_passport.json',
            'energy/fixtures/energy_consumer_type.json',
        ]

        path_fix = 'energy/fixtures/energy_fixtures.json'
        file_fix = open(path_fix, 'w')

        fixtures = []

        for path_file in files:
            file_json = open(path_file)
            fixtures = fixtures + json.load(file_json)
            file_json.close()

        json.dump(fixtures, file_fix, indent=2)
        file_fix.close()

        from django.core.management import execute_from_command_line
        execute_from_command_line(["manage.py", "loaddata", path_fix])

    operations = [
        migrations.RunPython(load_orum_types)
    ]
