# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_auto_20160120_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orumtype',
            name='formula',
            field=models.IntegerField(choices=[(1, '\u041f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u044b\u0439 \u0440\u0430\u0441\u0445\u043e\u0434'), (3, '\u0420\u0430\u0441\u0445\u043e\u0434 * \u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0434\u043d\u0435\u0439 * \u0427\u0430\u0441\u044b'), (2, '\u0420\u0430\u0441\u0445\u043e\u0434 * \u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0434\u043d\u0435\u0439')], verbose_name='\u0424\u043e\u0440\u043c\u0443\u043b\u0430'),
        ),
        migrations.AlterField(
            model_name='orumtype',
            name='title',
            field=models.CharField(max_length=31, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
