# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0004_auto_20160122_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='old_id',
            new_name='number_in_t2',
        ),
    ]
