# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0005_auto_20160122_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='name',
            field=models.CharField(max_length=160, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u043f\u043e\u0442\u0440\u0435\u0431\u0438\u0442\u0435\u043b\u044f'),
        ),
    ]
