# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0006_auto_20160129_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meter',
            options={'verbose_name': '\u0421\u0447\u0435\u0442\u0447\u0438\u043a', 'verbose_name_plural': '\u0421\u0447\u0435\u0442\u0447\u0438\u043a\u0438'},
        ),
        migrations.AlterField(
            model_name='consumer',
            name='type',
            field=models.IntegerField(choices=[(0, b'\xd0\xae\xd1\x80\xd0\xb8\xd0\xb4\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xbb\xd0\xb8\xd1\x86\xd0\xbe'), (1, b'\xd0\x91\xd1\x8b\xd1\x82\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb9 \xd0\xbf\xd0\xbe\xd1\x82\xd1\x80\xd0\xb5\xd0\xb1\xd0\xb8\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8c')], verbose_name='\u0422\u0438\u043f \u043f\u043e\u0442\u0435\u0440\u0431\u0438\u0442\u0435\u043b\u044f'),
        ),
    ]
